# Write a Pandas program to find and drop the missing values from the given dataset
ï‚· to remove the duplicates from the given dataset

In [1]:
#216270307011
#YASH S YOGANANDI
import pandas as pd
df=pd.read_csv("/kaggle/input/nifty50-stock-market-data/HDFC.csv");
data_frame=pd.DataFrame(df);
data_frame.dropna(inplace=True)
print(data_frame)

            Date Symbol Series  Prev Close     Open     High      Low  \
2850  2011-06-01   HDFC     EQ      684.05   676.55   692.95   676.55
2851  2011-06-02   HDFC     EQ      689.10   681.05   684.70   676.60
2852  2011-06-03   HDFC     EQ      680.00   678.50   683.05   658.25
2853  2011-06-06   HDFC     EQ      660.05   659.95   674.10   659.15
2854  2011-06-07   HDFC     EQ      670.65   668.00   674.65   662.30
...          ...    ...    ...         ...      ...      ...      ...
5301  2021-04-26   HDFC     EQ     2497.35  2500.00  2534.10  2483.20
5302  2021-04-27   HDFC     EQ     2509.80  2494.15  2526.80  2486.25
5303  2021-04-28   HDFC     EQ     2518.40  2516.10  2609.00  2508.30
5304  2021-04-29   HDFC     EQ     2577.00  2590.90  2628.00  2533.00
5305  2021-04-30   HDFC     EQ     2538.85  2503.10  2525.00  2411.10

         Last    Close     VWAP   Volume      Turnover    Trades  \
2850   689.00   689.10   688.38  1204308  8.290230e+13   38210.0
2851   680.25   680.00   680.53  1100046  7.486138e+13   20300.0
2852   659.15   660.05   668.24  2170805  1.450628e+14   33742.0
2853   671.00   670.65   668.56  2854529  1.908411e+14   38749.0
2854   667.35   669.20   669.01  1865334  1.247924e+14   35136.0
...       ...      ...      ...      ...           ...       ...
5301  2502.00  2509.80  2508.07  3916088  9.821805e+14  121028.0
5302  2514.00  2518.40  2509.18  2040799  5.120730e+14  102250.0
5303  2575.00  2577.00  2574.21  3407461  8.771527e+14  117425.0
5304  2539.70  2538.85  2569.65  3005468  7.722995e+14  132826.0
5305  2433.25  2420.10  2445.94  6024595  1.473581e+15  224454.0

      Deliverable Volume  %Deliverble
2850            562346.0       0.4669
2851            637219.0       0.5793
2852           1435985.0       0.6615
2853           2007268.0       0.7032
2854           1207216.0       0.6472
...                  ...          ...
5301           2440395.0       0.6232
5302           1040749.0       0.5100
5303           1815110.0       0.5327
5304           1472924.0       0.4901
5305           3839105.0       0.6372

[2456 rows x 15 columns]

# Write a Pandas program to remove the duplicates from the given dataset

In [2]:
#216270307011
#YASH S YOGANANDI
import pandas as pd
df=pd.read_csv("/kaggle/input/wrong-data/wrong_data.csv");
data_frame=pd.DataFrame(df)
miss_data=data_frame.drop_duplicates();
miss_data

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0